### ISSUE TITLE
Escape ampersands (&) in address lines in JOSM links

### ISSUE THREAD

**Issue by rjw62** [gregrs-uk/fhrs-osm-stats#1]
It appears that ampersands appearing in address lines are not escaped when included in the "Add tags in JOSM" URL link. Without being escaped, they mess things up in JOSM, as the ampersand is treated as the end of the addtags query variable. See for example, the link for http://ratings.food.gov.uk/business/en-GB/920810/ in http://gregrs.dev.openstreetmap.org/fhrs/district-168.html

`http://localhost:8111/load_object?objects=w190096138&addtags=fhrs:id=920810|fixme:addr1=B & M Retail Ltd|fixme:addr2=Milton Road South|fixme:addr3=STOWMARKET|fixme:addr4=Suffolk|addr:postcode=IP14 1EJ |source:addr=FHRS Open Data`

**Comment by gregrs-uk** [comment]
Thanks Robert. I've added your comment to [this existing issue in python-fhrs-osm](https://github.com/gregrs-uk/python-fhrs-osm/issues/48) as this repository is just for the graphs. You may want to subscribe to the other issue.
