### ISSUE TITLE
Handle ; column separated fhrs:id fields where more than one id for single location

### ISSUE THREAD

**Issue by EdLoach** [gregrs-uk/fhrs-osm-stats#2]
It is possible I'm tagging this situation wrong, but as an example:
[OSM way representing business](http://www.openstreetmap.org/way/191821917)
This seems to have been inspected as both [848651](http://ratings.food.gov.uk/business/en-GB/848651/) and [999268](http://ratings.food.gov.uk/business/en-GB/999268/) on the same day, with the only difference I can see is that one used 'and' and one uses '&', so I added both values separated by a ;

This is likely to show as a mis-match [as per other examples in the area](http://gregrs.dev.openstreetmap.org/fhrs/district-44.html)

**Comment by gregrs-uk** [comment]
Thanks Ed. I've added your comment to [this issue](https://github.com/gregrs-uk/python-fhrs-osm/issues/11) in the main python-fhrs-osm repository as this one's just for the graph pages.
